spring:
  application:
    name: gateway-service
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
      - id: shortener
        uri: lb://shortener
        predicates:
        - Path=/shortener/**
        filters:
        - AuthenticationFilter
        
      - id: identity-service
        uri: lb://IDENTITY-SERVICE
        predicates:
        - Path=/auth/**